[package]
name = "dancing_links_matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5", optional = true }
itertools.workspace = true

[dev-dependencies]
test-case = "3.3.1"

[features]
default = ["random"]
random = ["dep:rand"]
