[package]
name = "dancing_links_matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
itertools.workspace = true
log.workspace = true

[dev-dependencies]
test-case = "3.3.1"
bumpalo.workspace = true
