[package]
name = "cmd_common"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
clap.workspace = true
simple_logger.workspace = true
bumpalo.workspace = true
dancing_links_matrix = { path = "../dancing_links_matrix" }
