[package]
name = "nqueens"
version = "0.1.0"
edition = "2021"

[dependencies]
dancing_links_matrix = { path = "../dancing_links_matrix" }
itertools.workspace = true
logging_timer.workspace = true
simple_logger.workspace = true