[package]
name = "sudoku"
version = "0.1.0"
edition = "2024"

[dependencies]
dancing_links_matrix = { path = "../dancing_links_matrix" }
cmd_common = { path = "../cmd_common" }
itertools.workspace = true
logging_timer.workspace = true
clap.workspace = true
bumpalo.workspace = true